import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar/Navbar";
import TransitionProvider from "@/components/transitionProvider/TransitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by Mahmoud Ahmed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <link rel="icon" href="assets/favicon.png" sizes="any" />
        <TransitionProvider>
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
